steps:
  # Should be overritten by the projects if projects only support jdk 8
  # TestCase: Test that project (book address manager) has precedence
  mavenExecute:
    dockerImage: 'maven:3.6.3-jdk-11-slim'

stages:
  # Is required by project
  # TestCase: Test that shared config works by removing from the project itself
  backendIntegrationTests:
    credentials:
      - alias: 'MOCK_SYSTEM'
        credentialId: 'MY-MOCK-ERP'

  endToEndTests:
    appUrls:
      - url: 'https://approuter-cloudpot.cfapps.sap.hana.ondemand.com'
        credentialId: e2e-test-user-cf
        parameters: ['--NIGHTWATCH_ENV=chrome']
      - url: 'https://approuter-cloudpot.cfapps.sap.hana.ondemand.com'
        credentialId: e2e-test-user-cf
        parameters: ['--NIGHTWATCH_ENV=firefox']
    cfCreateServices:
      - serviceManifest: 'services-manifest.yml'
        space: 'Test'
    cfTargets:
      - space: 'Test'
        manifest: 'manifest-test.yml'
